#ifndef DISCORD_FFI_H
#define DISCORD_FFI_H

#pragma once

/* This file is generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Increment when changing the C ABI surface in a breaking way.
 */
#define DISCORD_FFI_ABI_VERSION 1

typedef enum DiscordErrorCode {
  DiscordOk = 0,
  DiscordNullPointer = 1,
  DiscordInvalidUtf8 = 2,
  DiscordInvalidUrl = 3,
  DiscordRuntimeInitError = 4,
  DiscordClientError = 5,
  DiscordSerializationError = 6,
  DiscordGatewayAlreadyRunning = 7,
  DiscordGatewayNotRunning = 8,
} DiscordErrorCode;

typedef struct DiscordClientHandle {
  uint8_t _private[0];
} DiscordClientHandle;

uint32_t discord_ffi_abi_version(void);

void discord_string_free(char *value);

enum DiscordErrorCode discord_client_new(const char *base_url,
                                         struct DiscordClientHandle **out_client,
                                         char **out_error);

void discord_client_free(struct DiscordClientHandle *client);

enum DiscordErrorCode discord_client_set_token(struct DiscordClientHandle *client,
                                               const char *token,
                                               char **out_error);

enum DiscordErrorCode discord_client_clear_token(struct DiscordClientHandle *client,
                                                 char **out_error);

enum DiscordErrorCode discord_client_current_user_json(struct DiscordClientHandle *client,
                                                       char **out_json,
                                                       char **out_error);

enum DiscordErrorCode discord_client_list_guilds_json(struct DiscordClientHandle *client,
                                                      char **out_json,
                                                      char **out_error);

enum DiscordErrorCode discord_client_list_channels_json(struct DiscordClientHandle *client,
                                                        const char *guild_id,
                                                        char **out_json,
                                                        char **out_error);

enum DiscordErrorCode discord_client_list_messages_json(struct DiscordClientHandle *client,
                                                        const char *channel_id,
                                                        uint8_t limit,
                                                        char **out_json,
                                                        char **out_error);

enum DiscordErrorCode discord_client_gateway_stream_start(struct DiscordClientHandle *client,
                                                          uint64_t intents,
                                                          char **out_error);

enum DiscordErrorCode discord_client_gateway_stream_stop(struct DiscordClientHandle *client,
                                                         char **out_error);

enum DiscordErrorCode discord_client_gateway_stream_next_event_json(struct DiscordClientHandle *client,
                                                                    char **out_json,
                                                                    char **out_error);

#endif  /* DISCORD_FFI_H */
