#ifndef OPENCORD_FFI_H
#define OPENCORD_FFI_H

#pragma once

/* This file is generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Increment when changing the C ABI surface in a breaking way.
 */
#define OPENCORD_FFI_ABI_VERSION 1

typedef enum OpenCordErrorCode {
  OpenCordOk = 0,
  OpenCordNullPointer = 1,
  OpenCordInvalidUtf8 = 2,
  OpenCordInvalidUrl = 3,
  OpenCordRuntimeInitError = 4,
  OpenCordClientError = 5,
  OpenCordSerializationError = 6,
} OpenCordErrorCode;

typedef struct OpenCordClient {
  uint8_t _private[0];
} OpenCordClient;

uint32_t opencord_ffi_abi_version(void);

void opencord_string_free(char *value);

enum OpenCordErrorCode opencord_client_new(const char *base_url,
                                           struct OpenCordClient **out_client,
                                           char **out_error);

void opencord_client_free(struct OpenCordClient *client);

enum OpenCordErrorCode opencord_client_set_token(struct OpenCordClient *client,
                                                 const char *token,
                                                 char **out_error);

enum OpenCordErrorCode opencord_client_clear_token(struct OpenCordClient *client, char **out_error);

enum OpenCordErrorCode opencord_client_token_copy(struct OpenCordClient *client,
                                                  char **out_token,
                                                  char **out_error);

enum OpenCordErrorCode opencord_client_current_user_json(struct OpenCordClient *client,
                                                         char **out_json,
                                                         char **out_error);

enum OpenCordErrorCode opencord_client_gateway_bot_json(struct OpenCordClient *client,
                                                        char **out_json,
                                                        char **out_error);

#endif  /* OPENCORD_FFI_H */
